import AuthStateProvider from "@/provider/AuthStateProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthStateProvider>{children}</AuthStateProvider>
      </body>
    </html>
  );
}
